Fixed Parsing error
Issue: Parsing error: Cannot find module 'next/babel'
Require stack:

Fix: add "next/babel" to extends to properly configure babel